version: '3.7'
services:
  rabbitmq:
    image: "rabbitmq:management" 
    ports:
      - "15672:15672"  # Management plugin UI port
      - "5672:5672"    # AMQP protocol port for message communication
    environment:
      RABBITMQ_DEFAULT_USER: "guest"  # Default RabbitMQ username
      RABBITMQ_DEFAULT_PASS: "guest"  # Default RabbitMQ password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent storage for RabbitMQ data

volumes:
  rabbitmq_data:
    driver: local  # Use local volume driver for persistent data storage